### PR TITLE
main.py: fix and update docstring

### PR DESCRIPTION
**Pull request by alick**

### CODE REVIEW

**Comment by sztsian** [comment]
Seems no functional changes. So merge without test.

**Comment by alick** [comment]
@sztsian 咦，为啥没有 merge commit 呢？

**Comment by sztsian** [comment]
@alick 我这儿显示 **_sztsian merged commit 3591d8d into FZUG:master 4 days ago**_ 啊

**Comment by alick** [comment]
我好像也看到了。不知道那天是什么情况……

**Pull request merged**
