### PR TITLE
main.py: fix auto gen date in main content of email (#13)

### PR DESCRIPTION
**Pull request by alick**

### CODE REVIEW

**Comment by alick** [comment]
Should fix #13

**Comment by alick** [comment]
谁帮忙测试下？

**Comment by Endle** [comment]
下周日的会议不出意外我能到，到时候我测试一下，然后merge这个pr

**Comment by alick** [comment]
这个还有人用么？
 @sztsian

**Comment by sztsian** [comment]
I don't think so, as meetbot send email to meetingminutes list automatically.
However, it does not hurt to merge it

**Pull request merged**
